services:
  - type: web_service
    name: carabin-quiz-backend
    env: node
    branch: main
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false   # ⚠️ à renseigner manuellement dans Render Dashboard

  - type: static_site
    name: carabin-quiz-frontend
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://carabin-quiz-backend.onrender.com/api
        