services:
  - type: web
    name: carabin-quiz-backend
    env: node
    branch: main
    rootDir: backend
    buildCommand: "npm ci"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
        
  - type: web
    name: carabin-quiz-frontend
    env: node
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s build"
    envVars:
      - key: REACT_APP_API_URL
        value: https://carabin-quiz-backend.onrender.com/api
