services:
  - type: web
    name: carabin-quiz-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: PORT
        value: 5000

  - type: web
    name: carabin-quiz-frontend
    env: node
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s build"
    envVars:
      - key: REACT_APP_API_URL
        value: https://carabin-quiz-backend.onrender.com/api
