services:
  - type: web
    name: carabin-quiz-backend
    env: node
    branch: main
    rootDir: backend
    buildCommand: "npm install --force"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET